Whole swathe of translations. Hopefully to the right fork this time?
riftcrystal/DDON-Translation pull request #11
Opened 2017-02-14 19:04 UTC by KomradeSpectre

Noticed Arisen Card isn't translated in the xml file, but is ingame, so perhaps disregard my changes to it if it's changed elsewhere.

2017-03-02 21:16 UTC, riftcrystal requested changes
Please address the tabs and indent issue that generally exists in all additions, aside from the other issues I've commented on.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/master/area1_spot_info.xml
> +	<translation>A stone bridge near Tel Village in Southern Hidell. When traffic to
When adding new lines for a translation, you need to take care with indents. White space isn't ignored, and will show up in-game.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/master/area1_spot_info.xml
> +	<translation>Hidell Church catacombs located to the east of Tel village. Previously visited by
This isn't normally an issue, but to make you aware of it: please use two spaces instead of actual tabs for indentation. This will keep diffs a bit cleaner because my translation pack builder tools will correct this (and require commits) to correct it.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/master/area1_spot_info.xml
> +</resource>
Please don't add a newline to the last line in the file.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/ui/AreaMaster_res.xml
> +
Dead space.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/ui/ArisenCard.xml
> +	<translation>Edit Profile</translation>
This entire file is likely a duplicate of ArisenCard_win.xml and is probably unused on PC. I'd suggest removing it from your commits entirely, and I can add a replication config for it on my end to mirror translations between ArisenCard.xml and ArisenCard_win.xml.

You also have numerous differences from the translations in ArisenCard_win.xml that I would consider conflicts.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/loading/loading_message_000.xml
> +</resource>
Please don't add a newline to the last line in the file.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/ui/option_res_win.xml
> +</resource>
Please don't add a newline to the last line in the file.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/ui/AreaMaster_res.xml
> +</resource>
Please don't add a newline to the last line in the file.

2017-03-02 21:16 UTC, riftcrystal commented on ui/00_message/ui/system_messasge_win.xml
> +</resource>
Please don't add a newline to the last line in the file.

2017-03-03 18:15 UTC, KomradeSpectre commented
Doing the requested changes currently. Seems the newline keeps either getting added by Notepad++ or some bug in TortoiseGit. I'm unaware of which one is causing it, but my guess is Notepad++. On that note, is there an alternative editor you'd suggest to use for making edits to the xml files?

2017-03-03 18:38 UTC, riftcrystal requested changes

2017-03-03 18:38 UTC, riftcrystal commented on ui/00_message/master/area1_spot_info.xml
> +  <translation>A large plain spread across central Lestania.
I apologize, when I said two spaces, I meant two spaces instead of using a tab, not only two spaces. Like this line would need four spaces.

2017-03-03 19:41 UTC, DaedalusGame commented
Can these caveats be added to the contributor guide in the readme?

2017-03-03 20:15 UTC, KomradeSpectre commented
I believe that's everything?
Lemme know if I overlooked anything you requested changed, I'll have another look myself as well.

2017-03-03 20:34 UTC, riftcrystal commented
@DaedalusGame Yeah, I'll add them. It's something I should have done before but with only two people working on it before it had gone discussed outside of GitHub.

2017-03-04 00:48 UTC, riftcrystal approved these changes

2017-03-04 00:49 UTC, merged