Whole Swathe of Translations 2
riftcrystal/DDON-Translation pull request #12
Opened 2017-03-10 06:46 UTC by KomradeSpectre

Completely translated Augments/Augment Names (Also corrected a few wrongslations.)
Mostly translated p0003.xml .
Mostly translated Caplink stuff (why? I'm not sure myself.)
Only a few Item Info translations.
Fixed a misnomer (Demon Unrefined Wine to Unrefined Demon Wine)
Fixed a misnomer I made (Hidell Catacombs referenced Hidell Church instead of Hidell Chapel)
Fixed some misnomers in normal skill stuff (Magic to Magick, Hack to Carve on the Seeker, etc)
Translated some Bazaar stuff.

Format changed in accordance to desired changes in last PR.
If I missed anything in regards to this, please let me know. I'm gonna take a small
break from translating (a day or so) before completely translating skills haha

2017-03-10 06:47 UTC, KomradeSpectre commented
Weird that it's tracking old commits.

2017-03-13 12:19 UTC, KomradeSpectre commented
Figured that &lt;KEYM&gt; and &lt;PADM&gt; must be cases where it displays the specific section (keyboard based or gamepad based) when these tags lead the section. Fixed the spirit lancer stuff accordingly. If I'm wrong on this, let me know.

2017-03-14 09:41 UTC, riftcrystal requested changes

2017-03-14 09:41 UTC, riftcrystal commented on ui/00_message/skill/custom_skill_info_01.xml
> +LV.６: Increases the number of hits in the attack, and changes
Please change the fullwidth character to the regular character (in this case, LV.６should be LV.6). This applies to any other translated messages as well.

2017-03-14 09:41 UTC, riftcrystal commented on ui/00_message/common/item_name.xml
> +    <translation>Unrefined Demon Wine</translation>
You're certain this is an error? I try to match the DDON translation wikidot for easier end-user use.

2017-03-14 09:41 UTC, riftcrystal commented on ui/00_message/skill/ability_info.xml
> +LV5～6: Increases blow power.&lt;/COL&gt;</translation>
Please change the fullwidth character to the regular character (in this case, ～ should be ~). This applies to any other translated messages as well.

2017-03-14 09:41 UTC, riftcrystal commented on ui/00_message/skill/ability_info.xml
> +Heal Aura / Greater Heal Aura / Ride Heal Aura.
I don't think the spaces around the / between skill names is necessary here.

2017-03-14 09:41 UTC, riftcrystal commented on ui/00_message/skill/normal_skill_name_06.xml
> +    <translation>Magick Bolts</translation>
Why balls => bolts?

2017-03-14 09:41 UTC, riftcrystal commented on ui/00_message/skill/normal_skill_name_08.xml
> +    <translation>&lt;PADM&gt;Seeker Aim&lt;KEYM&gt;Change Stance(Seeker Aim)</translation>
Need a space before the parenthesis for Change Stance.

2017-03-14 09:41 UTC, riftcrystal commented on ui/00_message/ui/Caplink_res.xml
> +    <translation>Invited %s .</translation>
Errant space here before the period.

2017-03-14 09:41 UTC, riftcrystal commented on ui/00_message/ui/Caplink_res.xml
> +    <translation>Sent a Capfriend request to %s .</translation>
Errant space here before the period.

2017-03-15 01:49 UTC, KomradeSpectre commented on ui/00_message/skill/normal_skill_name_06.xml
> +    <translation>Magick Bolts</translation>
It's a skill mirror from the other game. Bolts make sense if we have skill mirror names from DD:DA in here.

2017-03-15 01:51 UTC, KomradeSpectre commented on ui/00_message/common/item_name.xml
> +    <translation>Unrefined Demon Wine</translation>
I'm certain that's a grammatical error. If that's how the White Dragon Temple translated it, they mistranslated it.

2017-03-15 02:01 UTC, KomradeSpectre commented on ui/00_message/common/item_name.xml
> +    <translation>Unrefined Demon Wine</translation>
Not that it's the first mistranslation I've seen, but I don't really have all the time to go through and catch all of them haha

2017-03-15 02:02 UTC, KomradeSpectre commented on ui/00_message/skill/normal_skill_name_06.xml
> +    <translation>Magick Bolts</translation>
For example, Devastate being in the warrior's skills despite the text of the skill not meaning Devastate.

2017-03-15 12:32 UTC, DaedalusGame commented on ui/00_message/common/item_name.xml
> +    <translation>Unrefined Demon Wine</translation>
From what I gather, it's referring to unfiltered/unrefined demon sake
The literal translation is oni doburoku; i don't think i need to explain oni here.
Doburoku is an unrefined sake that can easily be made at home from steamed rice, kōji, water and yeast. Creation of this sake was outlawed during the meiji period apparently.

Apart from this, grammatically, i think both of these are correct but Unrefined Demon Wine sounds better. It's unrefined "wine"(sake) made by demons.

2017-03-15 15:06 UTC, riftcrystal approved these changes

2017-03-15 15:07 UTC, merged