Full skill, augment, and tactics trial translations
riftcrystal/DDON-Translation pull request #14
Opened 2017-03-19 19:31 UTC by KomradeSpectre

Another swathe of translations for you. If you know how to prevent the old commits from showing up in the pull, please let me know because I feel pretty embarrassed that they're continuously there haha.

2017-03-20 01:23 UTC, riftcrystal commented
@KomradeSpectre Could try `git pull --rebase; git push -f origin master`.

2017-03-20 09:43 UTC, KomradeSpectre commented
It doesn't include the old commits in the files changed though, so it's fine to pull still (after checking for anything I may have done wrong). I'm just confused on where I should focus next to be honest.

2017-03-22 10:26 UTC, KomradeSpectre commented
Seems one or two tactics trials made their way under my nose. To my knowledge there was only 1 per class. I'll fix this issue by translating the ones I forgot, and will commit it here.

2017-03-24 19:57 UTC, riftcrystal requested changes

2017-03-24 19:57 UTC, riftcrystal commented on ui/00_message/quest/q00000002.xml
> +    <translation>【Tip: About New Main Quests】
Would be good to move the 【】 over to [].

2017-03-24 19:57 UTC, riftcrystal commented on ui/00_message/skill/custom_skill_command_03.xml
> -</original>
Don't edit original text. Even if it has formatting mistakes.

2017-03-24 21:33 UTC, KomradeSpectre commented on ui/00_message/skill/custom_skill_command_03.xml
> -</original>
That was a mistake on my behalf, not intentional.

2017-03-24 21:36 UTC, riftcrystal commented on ui/00_message/skill/custom_skill_command_03.xml
> -</original>
That's fine, just pointing it out. My tooling requires original text to be left alone for things like merging in patch changes, etc.

2017-03-24 21:38 UTC, KomradeSpectre commented on ui/00_message/skill/custom_skill_command_03.xml
> -</original>
I'll fix it in a moment.

2017-03-24 21:47 UTC, KomradeSpectre commented
I think that should be good? Lemme know if you catch anything else. I try to learn from the mistakes I make on here haha

2017-03-25 01:30 UTC, merged

2017-03-25 01:30 UTC, riftcrystal commented
There will probably be necessary formatting changes to be done (wrapping, et al), but looks good.