A few tutorials
riftcrystal/DDON-Translation pull request #16
Opened 2017-04-12 19:56 UTC by SerLeighKnave

I translated a few of the tutorials.  If I've got the formatting down, I'll try to do a bigger lump of them next time.

Almost all of the ability/skill stuff I did got ditched because @KomradeSpectre got there first >:(  So there's almost nothing in those commits.

2017-04-12 22:41 UTC, riftcrystal requested changes

2017-04-12 22:41 UTC, riftcrystal commented on ui/00_message/skill/custom_skill_info_03.xml
> +Power greatly increases if released as charge reaches max.
Feel like this would be better worded as "Power greatly increases if released as maximum charge is reached."?

2017-04-12 22:41 UTC, riftcrystal commented on ui/00_message/tutorial_guide/steps/tutorial_guide_step24.xml
> +(Switch between Detail/Field/Region)
I don't think () is a good analogue for ＜＞ in this case.

Perhaps just like: `"Switch between Detail/Field/Region"` or `Switch between Detail/Field/Region:`?

Beside that, it should probably be `Switching between Detail/Field/Region` or `Detail/Field/Region Switch`.

2017-04-12 22:41 UTC, riftcrystal commented on ui/00_message/tutorial_guide/steps/tutorial_guide_step29.xml
> +From the Game Menu[&lt;KC UI_GAME_MENU&gt;], in "Communication"->"Phrases" or "Emotes"
Seems like you reversed the order of the icon and Game Menu here?

2017-04-12 22:41 UTC, riftcrystal commented on ui/00_message/tutorial_guide/steps/tutorial_guide_step8.xml
> +	<translation>The [&lt;KC UI_GAME_MENU&gt;]Game Menu
Probably should be a space after the `]` before `Game Menu`.

2017-04-13 01:37 UTC, SerLeighKnave commented
Should all be fixed now, hopefully.

2017-04-13 22:58 UTC, KomradeSpectre commented
My work should be much slower over these next few weeks as I'm learning the Japanese alphabet to aid in my translations, so go hog wild haha

2017-04-14 00:03 UTC, riftcrystal commented
@SerLeighKnave My comment regarding `()`/`＜＞` needs to be applied to any other edits you have made. I meant to indicate that.

2017-04-14 00:03 UTC, riftcrystal approved these changes

2017-04-14 00:05 UTC, merged

2017-04-14 03:23 UTC, SerLeighKnave commented
My reading ability is pretty garbage because I mostly learned through too much anime and osmosis, so I know how that goes, heh.